apiVersion: apps/v1
kind: Deployment
metadata:
  name: with_app-deployment
spec:
  selector:
    matchLabels:
      app: with_app
  replicas: 1
  template:
    metadata:
      labels:
        app: with_app
    spec:
      containers:
      - name: with_app
        image: chirag658/main_with_optimization:latest