apiVersion: apps/v1
kind: Deployment
metadata:
  name: without_app-deployment
spec:
  selector:
    matchLabels:
      app: without_app
  replicas: 1
  template:
    metadata:
      labels:
        app: without_app
    spec:
      containers:
      - name: without_app
        image: chirag658/main_without_optimization:latest